### ISSUE TITLE
Linux Configuration

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#1]
Nice package! 

Can you, please, expand the "ODBC Drivers for caché" section from README?  How to install and setup the caché odbc driver? The official docs from Intersystem is very tricky about how to install! 

https://github.com/jeandormehl/laracache#odbc-drivers-for-cach%C3%A9

I am getting `SQLSTATE[IM002] SQLConnect: 0 [unixODBC][Driver Manager]Data source name not found, and no default driver specified` , probably because "libcacheodbcur6435" is not properly installed

**Comment by jeandormehl** [comment]
Hi

Thanks for interest.
Sure, I will add the steps I used to install the ODBC drivers on Linux soon

**Comment by robsontenorio** [comment]
I would like to collaborate actively. Can I be in touch with you? Slack, Twitter,
Telegram ... (@robsontenorio)

**Comment by jeandormehl** [comment]
Sure, Ill contact you on Slack soon.

Issue closed by 45d1ba3c84a82fc8df9901ce119a0d8dd67314b3
