### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by WBDC** [jeandormehl/laracache#10]
Hi, 
Could you please add support for Laravel 6?

![image](https://user-images.githubusercontent.com/50083290/65980284-c0947100-e46e-11e9-8e24-d6035f3de778.png)

**Comment by jeandormehl** [comment]
Hi @WBDC 

Will look into it this weekend.
Should be implemented by Monday.

**Comment by WBDC** [comment]
Hi @jeandormehl , 

Have you got any update on this?

Many thanks

**Comment by jeandormehl** [comment]
Closed by https://github.com/jeandormehl/laracache/commit/e6976083edcc7ae84de423f0c9450a4eaa90062e

**Comment by WBDC** [comment]
Hi @jeandormehl, 

I've tried to install it, but still getting the below. 

![image](https://user-images.githubusercontent.com/50083290/66378663-d8f31700-e9ab-11e9-99a5-11b5b1fa009f.png)

**Comment by jeandormehl** [comment]
Hi

The composer.json should now correctly install both v5 and v6 of the illuminate packages.
You still having a problem?

Is v1.0.1 of the package installed?

**Comment by WBDC** [comment]
No, its not installed. 

This is the full output when I try to pull it via composer. 

`C:\wamp64\www\sqlChess>composer require jeandormehl/laracache
Using version ^1.0 for jeandormehl/laracache
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jeandormehl/laracache ^1.0 -> satisfiable by jeandormehl/laracache[1.0].
    - Conclusion: remove laravel/framework v6.0.4
    - Conclusion: don't install laravel/framework v6.0.4
    - jeandormehl/laracache 1.0 requires illuminate/database 5.7.* -> satisfiable by illuminate/database[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/database 5.7.17|don't install laravel/framework v6.0.4
    - don't install illuminate/database 5.7.18|don't install laravel/framework v6.0.4
    - don't install illuminate/database 5.7.19|don't install laravel/framework v6.0.4
    - don't install illuminate/database 5.7.x-dev|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.0|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.1|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.10|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.11|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.15|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.2|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.20|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.21|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.22|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.23|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.26|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.27|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.28|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.3|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.4|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.5|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.6|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.7|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.8|don't install laravel/framework v6.0.4
    - don't install illuminate/database v5.7.9|don't install laravel/framework v6.0.4
    - Installation request for laravel/framework (locked at v6.0.4, required as ^6.0) -> satisfiable by laravel/framework[v6.0.4].


Installation failed, reverting ./composer.json to its original content.`

Let me know how can I help you to resolve this. 

Thanks

**Comment by jeandormehl** [comment]
Sorry, had an explicit version specified in composer.json. Should pull correct version now from packagist.

**Comment by WBDC** [comment]
Thank you. Its installed now. 

![image](https://user-images.githubusercontent.com/50083290/66476305-272c1700-ea8d-11e9-8009-e8411f5a823c.png)
