### ISSUE TITLE
First query/connection issue

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#12]
Hi,

I am facing a issue where the first run/query/connection it a bit slow, but subsequents one get faster. 

Is there any configuration am i missing? Just used default `odbc.ini` on README.

**Comment by robsontenorio** [comment]
Just more context:

- Try some query
- Wait for 10 seconds.
- Try query again, this will be slow

**Comment by robsontenorio** [comment]
@jeandormehl  Just found this 

https://github.com/jeandormehl/laracache/blob/a521b0663299d24e4349f9bdce62963b0d6c2c1c/src/Pdo/Cache.php#L54

Is it supposed to ODBC driver to handle this disconnecting stuff?

**Comment by jeandormehl** [comment]
Hi @robsontenorio 

This is strange behavior indeed. 
I am not having problems with speeds at all.

Have you tried using a persistent connection?
You can set this by passing `PDO::ATTR_PERSISTENT` constant in configuration.

Also, check your session settings for the database using CSP.
You will want your sessions to stay open if persistent connections are used.

**Comment by robsontenorio** [comment]
@jeandormehl  Thanks for your help, but what do you mean "check your session settings for the database using CSP"? CSP?

**Comment by robsontenorio** [comment]
Just a issue with containers. I am using Docker. Sorry.
