### ISSUE TITLE
Issue with data within max column size

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#13]
I am experiencing a issue when retrieving fields within max column size defined on a table.

## How to reproduce:

- Considering you have a column "name" (VARCHAR 10) and it has exactly 10 chars
- When you try to select it from a eloquent query an error will be throw.
- If you delete 1 char, from this field on database and select again, no errors will be throw.

**Comment by robsontenorio** [comment]
According  README version is "libcacheodbcur6435.so". Just switched to "libcacheodbcur64.so".

Can you confirm  if there is a issue "within max column size" for recommended driver?

**Comment by jeandormehl** [comment]
Thanks for updating README.

Should be fixed by 8ff4b927395471
