### ISSUE TITLE
Random "Connection reset by peer"

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#19]
@jeandormehl  Do you see sometimes that problem? A few per month and it is momentaneous.

```
SQLSTATE[HY000] SQLDriverConnect: 12104 [Cache ODBC][State : HY000][Native Code 12104]
[libcacheodbcur6435.so]
Socket: Connection reset by peer (due to timeout or reboot)
```

Maybe an infraestructure problem in Caché DB / Network ? Or something we can do better on handling ODBC connections?

Could you share your full `odbc.ini` file?

**Comment by jeandormehl** [comment]
I have had this issue concerning ODBC connection as well.
I have tried to bypass this by setting the PDO connection to persistent but it still seems to happen from time to time.

I'm not sure how this one could be resolved from within the package, its a PHP/ODBC/Network issue as far as I understand it.

**Comment by jeandormehl** [comment]
[ODBC Data Sources]
cache=cache

[cache]
Driver                = /usr/lib/intersystems/odbc/bin/libcacheodbcur6435.so
Description           = InterSystems Cache ODBC Connection
Protocol              = TCP
Query Timeout         = 1
Static Cursors        = 0
Authentication Method = 0

**Comment by robsontenorio** [comment]
Thank you!
