### ISSUE TITLE
DSN string not built properly

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#2]
Here is my .ENV
```sh
DB_CONNECTION=isc
DB_HOST=10.0.1.2
DB_PORT=1972
DB_DATABASE=MYNAMESPACE
DB_USERNAME=user1
DB_PASSWORD=pass1
```

Just noticed  `$dsn` value is only`odbc:cache` . Is it supposed to be a full DSN string?

```php
class Cache extends PDO
{
public function __construct($dsn, $username, $password, array $options = [])
    {
        // must call pdo constructor
        parent::__construct($dsn, $username, $password, $options);
```

Am i missing something? Can you, please,  provide a real configuration sample?

**Comment by robsontenorio** [comment]
Just realized some .env vars are useless, and i needed to set DB_DSN, otherwise it will fail.

```sh
DB_CONNECTION=isc
DB_DSN="odbc:Driver=Default;Server=10.0.1.2;Port=1972;Database=MYNAMESPACE"
#DB_HOST=10.0.1.2
#DB_PORT=1972
#DB_DATABASE=MYNAMESPACE
DB_USERNAME=
DB_PASSWORD=
```
It can be solved if the DSN is built based on another .env vars.

**Comment by jeandormehl** [comment]
I will look into this and the reasoning I had the setup as such.
I do recall something about the /etc/odbc.ini with the unixODBC package on Ubuntu and the way PDO receive the DSN.

Will investigate and post my findings

**Comment by robsontenorio** [comment]
Probably you hardcoded your connection setup on odbc.ini file. I do prefer don’t do that. Because I am using Linux a Docker images and each  project has a different connection setup. (Data source)

As a said a buildDns() based on .env vars or something like this would be enough.

**Comment by jeandormehl** [comment]
Good idea, will implement this over the weekend and test.

**Comment by jeandormehl** [comment]
Had a look into this problem today and made some changes.
Please refer to 2c80ed1e2b858cd085b62bbec6559465770544d2 and give me feedback.
