### ISSUE TITLE
[PHP 8] PDO fetchAll() incompatible signature

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#24]
Hi,

Have you managed to upgrade sucessfully to PHP 8.0?

cc @robsontenorio @liamjcooper 

![image](https://user-images.githubusercontent.com/118955/130860866-3e6952d4-28c4-4c8e-920e-e33bc4e20ed0.png)

**Comment by liamjcooper** [comment]
Not yet, no. I could take a look though, was there any specific query that triggered this, or does it always throw this exception?

**Comment by robsontenorio** [comment]
@liamjcooper thanks for answering. 

Just any simple query like User:all()

**Comment by jeandormehl** [comment]
Hi Robson

Yes, the signature for the PDO function fetchAll has changed in PHP 8.0.
We will need to change the signature everywhere in the code base to match
the new PHP style by checking whether the user is using PHP > 7.

I am away at the moment on business, no idea when I'll have a chance to
look at this.
