### ISSUE TITLE
ODBC driver download

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#25]
Hi, guys!

It seems FTP for downloading Caché ODBC drivers is not working anymore.

ftp://ftp.intersys.com/pub/cache/odbc/2018/ODBC-2018.1.0.184.0-lnxubuntux64.tar.gz

Could you please share ODBC drivers?

Cc @liamjcooper @jeandormehl

**Comment by SharonPerkins** [comment]
Hi could you please assist me in finding where I can download the 32 bit version for windows?

**Comment by maki-markie** [comment]
hi there i also need the ODBC driver version 2017 and 2018 (and latest) füor WINDOWS.

thanks a lot!

**Comment by jeandormehl** [comment]
Hi folks. Sorry, I haven't used Cache in a couple of years. Maybe one of
the other collaborators can assist

**Comment by KevinTay1** [comment]
https://github.com/jeandormehl/laracache/issues/25

https://github.com/intersystems-community/iris-driver-distribution/tree/main/ODBC

https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=BNETODBC

https://intersystems-community.github.io/iris-driver-distribution/
