### ISSUE TITLE
Pagination (%vid)

### ISSUE THREAD

**Issue by robsontenorio** [jeandormehl/laracache#6]
Although it is a valid test, the resulting query does not make sense.

https://github.com/jeandormehl/laracache/blob/7214330aaef273ad92511d543c9c4e4b93bd182f/tests/CacheQueryBuilderTest.php#L505-L510

Just executed in Caché (2016) and it does not return the right result, because "top 10" (limit 10) is fixed and it will always get same first top 10 results. So, pagination never happens. Any tricks?

**Comment by jeandormehl** [comment]
Hi.

I have made a change regarding this.
Found this post on the InterSystems community and now I select by top all:
[%VID and Pagination](https://community.intersystems.com/post/use-vid-row-selection-syntax)

Please let me know if this rectifies the issue.

**Comment by robsontenorio** [comment]
TOP ALL worked. But, Caché does not "optimize" the pagination mechanism :( There is nothing laracache can do to solve it :)
